### ISSUE TITLE
[Feature/Idea]: Allow WinGet Releaser GitHub Action to run on any event

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#1]
### What would you like to see changed/added?

The Winget releaser action can currently only run if the workflow is a [release event](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/bec564d5e5347ecbfafe2e5af655f15e1f99183a/winget-pkgs-automation/releaser-action/action.yml#L31) and a [released event type](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/bec564d5e5347ecbfafe2e5af655f15e1f99183a/winget-pkgs-automation/releaser-action/action.yml#L34), meaning the workflow has to look like this:
```yml
on:
  release:
    types: [released]
```

In my project, I have a [workflow ](https://github.com/russellbanks/HashHash/blob/main/.github/workflows/release.yml)that runs whenever there's a new release, builds the app, and then uploads the artifacts to the release. The Windows run takes the longest usually, up to 5 minutes. This isn't ideal as the WinGet Releaser action has a wait time of [2.5 minutes](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/bec564d5e5347ecbfafe2e5af655f15e1f99183a/winget-pkgs-automation/releaser-action/action.yml#L94) before it should fail because it is unable to find the correct artifact, so I can pretty much guarantee that I am going to have to re-run it every time.

Therefore, to work around this, I could use the on: [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) to ensure that it will run after the Windows artifacts have been built and uploaded:
```yml
on:
  workflow_run:
    workflows: [Release]
    types:
      - completed
```

Therefore, allowing the WinGet Releaser GitHub Action to run on the workflow_run event, I won't have to re-run the action every time I make a release.

**Comment by ghost** [comment]
Hello @russellbanks, thank you for submitting an issue!

**Comment by vedantmgoyal9** [comment]
I had already observed this issue on a couple of other repositories too, and am already working on a new retry logic. The action is limited to very specific event types to prevent spamming of pull requests at winget-pkgs repository.

BTW, thanks for telling me about `workflow_run` event, will add an exception for it.

Updated workflow (work-in-progress): https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/test/winget-pkgs-automation/releaser-action/action.yml

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @russellbanks for ideas

**Comment by vedantmgoyal9** [comment]
@russellbanks I was testing the action with the `workflow_run` event, but the problem is the action won't be able to get the release information automatically as it does now and my main concern while creating the action was only that a user would not have to supply everything as an input for the action.

Maybe the new retry logic can work for you, and if I will be able to find a way to do it without increasing the number of *required* inputs, I will surely add it. For now, I will keep it for the future.

**Comment by russellbanks** [comment]
Thank you for looking into this! I've had a look at the new retry logic and the wait time is definitely long enough for my use case.

**Comment by vedantmgoyal9** [comment]
Thanks! I will push it to v1.0.0 after some more testing.

**Comment by russellbanks** [comment]
I've tried out the longer wait time it works much better, thank you!

**Comment by vedantmgoyal9** [comment]
@russellbanks, I've found a way to make the action work on any event. I'll update the action when I can get some free time 👍🏻

**Comment by russellbanks** [comment]
> @russellbanks, I've found a way to make the action work on any event. I'll update the action when I can get some free time 👍🏻

Since this original issue, I have actually been achieveing this by doing `needs: [ build_release ]` (only run when my build workflow is done), like OneFetch does. However, this would be super useful for getting other repositories to use WinGet Releaser, as they likely would be able to integrate it easier into their existing workflows :D

**Comment by vedantmgoyal9** [comment]
A new input will be required if the workflow is not running on the release event: `release-tag`. Workflows triggering on:
```yaml
on:
  push:
    tags:
      - v* # not exactly, you get the idea...
```
the value for `release-tag` can be set to `${{ github.ref }}`. For other events, you may have to refer to theGitHub's documentation.
