### ISSUE TITLE
[Bug]: Unhandled line endings after winget-pkgs change

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

WinGet Releaser changes all line endings in the repository in its commit:
- https://github.com/microsoft/winget-pkgs/pull/72137
- https://github.com/microsoft/winget-pkgs/pull/72112

The line ending change in winget-pkgs:
- https://github.com/microsoft/winget-pkgs/pull/71918

**Comment by russellbanks** [comment]
Should be resolved when the steps in https://github.com/microsoft/winget-pkgs/issues/72254 are in progress/completed

**Comment by vedantmgoyal9** [comment]
Although, some renormalization PRs are not merged yet, but I think this is resolved now.
