### ISSUE TITLE
[Feature/Idea]: Use custom Winget Releaser PR body

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#101]
### What would you like to see changed/added?

Bring back this PR body to differentiate Winget Releaser PRs from Komac:
> ### Pull request has been automatically created using 🛫 [WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser).

**Comment by vedantmgoyal9** [comment]
Implemented in 900681d16356d7f70aab4b4b05be0e4aa5feb66f
