### ISSUE TITLE
[Bug]: Spell checking runs for 3rd party packages

### ISSUE THREAD

**Issue by daiyam** [vedantmgoyal2009/winget-releaser#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

I've updated VSCodium to the `releaser-v2`.
I have found out that the `Spell checking` workfklow is running on packages other than `VSCodium`. Like `vim.vim version 9.0.1376` or `OrpheusTechnologyLtd.ProWritingAid.OfficeAddIn...`
https://github.com/VSCodium/winget-pkgs/actions

Something isn't right!

Can you look into it? Thx

**Comment by vedantmgoyal9** [comment]
@Trenly should the spell check workflow run on forks and that too on other branches, or should we restrict it to run on `push` and `pull_request` events that happen on `microsoft/winget-pkgs` only?

cc @jsoref @denelon

**Comment by jsoref** [comment]
I mean, you could change the workflow to use `paths` to limit which files github decides are worthy of triggering the workflow.

What makes the fact that the workflow runs problematic in your view? You aren't billed for it, and it isn't complaining about them.

**Comment by daiyam** [comment]
Yes, it's disturbing to receive alerts about packages that I don't manage.

@vedantmgoyal2009 Could we disable the `Spell Checking` workflow when only the version number has been changed?

**Comment by vedantmgoyal9** [comment]
I think you'll have to disable actions on your fork.

**Comment by vedantmgoyal9** [comment]
@daiyam is it still troubling you? I guess the only solution is that you disable the spell-check workflow on your fork.

**Comment by daiyam** [comment]
Yes. Disabling the actions is solving the issue. But I'm still battling with the issue at https://github.com/vedantmgoyal2009/winget-releaser/issues/119#issuecomment-1475843579
