### ISSUE TITLE
[Bug]: non-0 exit codes don't fail the workflow

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Komac has a non-zero exit code if it didn't complete successfully, usually an exit code of 1. If this happens, the action should fail too.

**Comment by sitiom** [comment]
Here is a good example here: https://github.com/rclone/rclone/actions/runs/4416776915/jobs/7741540077#step:2:13. The Windows binaries weren't available, and thus Winget Releaser should fail, but it didn't.

**Comment by russellbanks** [comment]
> The Windows binaries weren't available, and thus Winget Releaser should fail, but it didn't.

Similar thing happened with the workflow ran on Komac itself when I added the machine installer so the input was 2 installers but there was only 1 previous installer. Komac threw an error but the workflow was shown as successful.

**Comment by vedantmgoyal9** [comment]
I've fixed this, but I'll request @russellbanks and @sitiom to confirm in some workflow runs on repositories for extra surety.

**Comment by sitiom** [comment]
Same issue:
https://github.com/sitiom/Win32-OpenSSH/actions/runs/4485054079/jobs/7886196940
![image](https://user-images.githubusercontent.com/56180050/226771900-5f603bef-04bd-4a4d-9afe-4bb1180561e9.png)

**Comment by sitiom** [comment]
Same issue:
https://github.com/sitiom/Win32-OpenSSH/actions/runs/4485054079/jobs/7886196940
![image](https://user-images.githubusercontent.com/56180050/226771900-5f603bef-04bd-4a4d-9afe-4bb1180561e9.png)

I think this is a Komac issue, though. I've tested the same in the command-line, and it returned a success. @russellbanks
![image](https://user-images.githubusercontent.com/56180050/226772274-cd308bb8-9634-4bc0-8b82-6b761f7e8211.png)

**Comment by vedantmgoyal9** [comment]
@russellbanks the bug is from Komac. Waiting to see v1.3.1 🙂

**Comment by russellbanks** [comment]
The KDoc for CliktError says it defaults to 1 but checking the source code it defaults to 0. I've explicity added statusCode = 1 and verified the exit code works so I'll create 1.3.1.

**Comment by vedantmgoyal2009** [comment]
Ah, so that is from Clikt itself. Maybe you should file a there so that the issue is fixed from the root itself.

**Comment by vedantmgoyal9** [comment]
@sitiom can you please re-run https://github.com/sitiom/Win32-OpenSSH/actions/runs/4485054079/jobs/7886196940 & test again?

**Comment by sitiom** [comment]
Now it successfully fails
![image](https://user-images.githubusercontent.com/56180050/227399813-16446049-9b7d-4e29-a74d-90abdb0eb65b.png)

**Comment by russellbanks** [comment]
> Ah, so that is from Clikt itself. Maybe you should file a there so that the issue is fixed from the root itself.

Created https://github.com/ajalt/clikt/issues/402 and https://github.com/ajalt/clikt/pull/403
