### ISSUE TITLE
[Bug]: duplicate PR created with same version 

### ISSUE THREAD

**Issue by daiyam** [vedantmgoyal2009/winget-releaser#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

Since v2, duplicate PR are created when the first PR with the same version has not been merged.

https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+author%3Adaiyam+

**Comment by vedantmgoyal9** [comment]
cc @russellbanks

**Comment by russellbanks** [comment]
@vedantmgoyal2009 should I change Komac so that if a PR already exists (within the last two weeks) it won't create a PR? The functionality is there but it's ignored if the environment is a CI environment. As this is usually ran on releases, it should cover cases where it's ran again or multiple times.

**Comment by daiyam** [comment]
@russellbanks By experience, a PR can take several days to be validated.
Yes, if a PR already exists (with same version, created at any time), the PR shouldn't be created.

**Comment by vedantmgoyal9** [comment]
Fixed in https://github.com/russellbanks/Komac/releases/tag/v1.2.0

**Comment by russellbanks** [comment]
@daiyam, I think I am going to have to revert this behaviour as projects that release nightly versions, such as Neovim Nightly, aren't able to publish any to winget as they always update the same version with the new url.

Komac will identify it as having an existing pull request so will skip it.

**Comment by daiyam** [comment]
Can you limit to only opened PR?
Right now, it won't create a new PR for any PR even those which have been cancelled.

**Comment by russellbanks** [comment]
That makes sense. Thanks @daiyam, I'll change it to that.
