### ISSUE TITLE
[Feature/Idea]: Log command to invoke Komac to stdout

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#119]
### What would you like to see changed/added?

The command used to invoke Komac should be printed to stdout for debugging

**Comment by daiyam** [comment]
@vedantmgoyal2009 Do you think it's possible because I've still have the issue mentioned in https://github.com/vedantmgoyal2009/winget-releaser/issues/117#issuecomment-1470659804
