### ISSUE TITLE
[Bug]: Exception occured but did not exit workflow

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/nushell/nushell/actions/runs/4420475651/jobs/7750215179
![image](https://user-images.githubusercontent.com/56180050/225327079-5118c8e4-2d83-42b9-811d-0a7aa4ccba17.png)

An exception occurred but did not exit the workflow and stayed idle for 6 hours until the time limit canceled it. Possibly a bug in Komac's side? @russellbanks

**Comment by vedantmgoyal9** [comment]
Duplicate of #113

**Comment by sitiom** [comment]
That's a different bug, though. The action keeps running instead of exiting successfully, like in #113.

**Comment by vedantmgoyal9** [comment]
I think it should have been fixed in the refactoring done by @russellbanks in https://github.com/russellbanks/Komac/pull/136, but anyways, I don't think the bug is present here and probably should be fixed in Komac itself.
