### ISSUE TITLE
[Feature/Idea]: Make action run cross-platform

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#126]
### What would you like to see changed/added?

Komac is already cross-platform. The only thing that needs to be added in non-Windows platforms is proper MSI detection, as stated in https://github.com/russellbanks/Komac/issues/110.

Other than that, it works well. This would enable Winget Releaser to immediately run in a current deploy job (most likely `ubuntu-latest`) instead of having to separate it. I also think that `ubuntu-latest` runners have a shorter startup time than `windows-latest`; it would help for a shorter workflow run time.

**Comment by vedantmgoyal9** [comment]
I will wait until @russellbanks has fixed https://github.com/russellbanks/Komac/issues/110, because I don't want incorrect manifests created through my action. Although, nothing much is needed to do here except to update the docs and remove the condition: https://github.com/vedantmgoyal2009/winget-releaser/blob/227c8615e56c29da23d1da19206844bccb698b29/main.ts#L10-L13 so that can be done anytime once issues are fixed in Komac itself.

**Comment by russellbanks** [comment]
MSI support on non-windows platforms was added in 1.4.0 of Komac. The lack of a token storage implementation on other platforms than Windows doesn't matter as WinGet Releaser always provides a token to Komac so the token never needs to be stored anywhere.

**Comment by sitiom** [comment]
Gonna have to update the readme too (and maybe some testing to see if it works fine?)

**Comment by vedantmgoyal9** [comment]
I've already updated however if something is left, you can always open a PR. @russellbanks it's time to test Komac on Linux platforms 😁🥳

**Comment by sitiom** [comment]
Some issues: https://github.com/russellbanks/Komac/issues/110#issuecomment-1575469984

**Comment by sitiom** [comment]
> I've already updated however if something is left, you can always open a PR.
- https://github.com/vedantmgoyal2009/winget-releaser/pull/168

**Comment by sitiom** [comment]
Works (except for the other unfixed bug in #167):
- https://github.com/pnpm/pnpm/pull/6630

**Comment by vedantmgoyal9** [comment]
@sitiom If you are updating all workflows to use Linux runner, according to https://github.com/russellbanks/Komac/issues/110#issuecomment-1483946680, I would advise not to change if that repository has an MSI installer. It might generate incorrect manifests in some cases. Windows would be still the preferred choice.
