### ISSUE TITLE
[Bug]: Action failing with GHFileNotFoundException 

### ISSUE THREAD

**Issue by repolevedavaj** [vedantmgoyal2009/winget-releaser#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is the first time I am using this plugin, so maybe I am doing something wrong. 

The action crashes because of the following error:
```
Exception in thread "main" org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/Project-Env/winget-pkgs/branches/refs/heads/ProjectEnv.ProjectEnvCli-3.15.0-4A5D6DD8E7851174D4A4025F5DAC4992 {"message":"Branch not found","documentation_url":"https://docs.github.com/rest/branches/branches#get-a-branch"}
```

This is the workflow file I have implemented: https://github.com/Project-Env/project-env-cli/actions/runs/4611714836/workflow

Example run: https://github.com/Project-Env/project-env-cli/actions/runs/4611714836/jobs/8151859946

**Comment by repolevedavaj** [comment]
I am using a classic token with the following scopes:
* repo
* workflow

Its a token of my account. The repo where I want to use the action is in a different organisation.

**Comment by vedantmgoyal2009** [comment]
cc @russellbanks

**Comment by russellbanks** [comment]
Could you try re-running it once? It appears that it is creating the manifest correctly, creating the branch correctly, but then failing to get the branch in order to commit it. This could be a one time issue that I just need to implement retry logic for.

**Comment by repolevedavaj** [comment]
Yes, now it worked: https://github.com/Project-Env/project-env-cli/actions/runs/4611714836/jobs/8173740045

Before I already tried to rerun it, but it failed again, so retry sounds like a good idea.

Thanks for taking a look!

**Comment by isaak654** [comment]
https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/900

**Comment by vedantmgoyal9** [comment]
It seems a fix was rolled out in Komac v1.5.0, so I hope this can be closed?

https://github.com/russellbanks/Komac/releases/tag/v1.5.0

Edit: closing since no failed workflow run was reported due to the bug.

**Comment by ilike2burnthing** [comment]
We have 4 different failed builds over at Jackett with Komac v1.5.1, including both from yesterday and today. Manually re-running the last two was successful, but it looks like this needs reopened.

**Comment by vedantmgoyal9** [comment]
This has been fixed in later releases of Komac. Also, a retry logic has been implemented to minimize the chances of workflow failing due to the bug.

**Comment by doug24** [comment]
I experienced the same problem reported here today on Aug 8.  It did finally work, but I had to rerun the job five times before it succeeded.

Link to job: https://github.com/dnGrep/dnGrep/actions/runs/5803181676/job/15731191331

Error: Exception in thread "main" org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/dnGrep/winget-pkgs/branches/refs/heads/dnGrep.dnGrep-4.0.69.0-D4097682DD7AB001623343E1E0FB23321747E109 {"message":"Branch not found","documentation_url":"https://docs.github.com/rest/branches/branches#get-a-branch"}

The link to the branch shown above is valid and opens the json file.

The log says: Created with WinGet Releaser v2 using Komac v1.9.1

**Comment by vedantmgoyal9** [comment]
@russellbanks Can you look into this? I think it's not a one-time issue since it has occured quite a few times.

**Comment by ilike2burnthing** [comment]
Occasionally getting the same issue with Jackett releases - https://github.com/Jackett/Jackett/actions/runs/5805503211/job/15736708127

Update: the last 2 days have failed and I retried the latest run up to attempt 10 before giving up.

**Comment by isaak654** [comment]
I can confirm the [GHFileNotFoundException](https://github.com/sandboxie-plus/Sandboxie/actions/runs/5846753711/job/15852272973#step:3:77) bug in the Sandboxie Classic 5.65.5 job using Komac v1.9.1.

I have just attempted to re-run it twice without success, so what should be done now to publish the Classic release?

EDIT: a third attempt the following day went well, hopefully this will not occur again.

**Comment by vedantmgoyal9** [comment]
I'll be creating a new winget manifests updater CLI, specifically for the action so that we can get around this issue. It will take at most ~2 weeks, and I hope such errors wouldn't happen after that.

**Comment by russellbanks** [comment]
Hi, this issue seems to be a rare issue that only happens on runners.

This should be fixed in the next version of Komac.

**Comment by vedantmgoyal9** [comment]
Well, automation uses the nightly version of Komac, and I can see runs being successful. Please release a version so that the action can be updated. I guess the "refactor downloading" commit has fixed the issue, but I'll keep the issue open for some more time, so that I'm sure that it doesn't happen anymore.

**Comment by ilike2burnthing** [comment]
> This should be fixed in the next version of Komac.

Would that be v1.10.1?

**Comment by russellbanks** [comment]
> Would that be v1.10.1?

The latest version is always the best to use, but the fixes for this were in 1.10.0. The patches in 1.10.1 were unrelated to this issue.

**Comment by ilike2burnthing** [comment]
My bad, I was looking at the commit labelled [1.10.0](https://github.com/russellbanks/Komac/commit/77cd79b8258c84ea7bef251b23edcdb45019738e) from 3wks ago rather than the [release](https://github.com/russellbanks/Komac/releases/tag/v1.10.0) from 2 days ago.

Winget-releaser actions have been working fine for the past 2 days, so it's looking good so far.

**Comment by vedantmgoyal2009** [comment]
@allcontributors
please add @repolevedavaj for bug
please add @ilike2burnthing for bug
please add @doug24 for bug
please add @isaak654 for bug

**Comment by vedantmgoyal2009** [comment]
@allcontributors
please add @repolevedavaj for bug.
please add @ilike2burnthing for bug.
please add @doug24 for bug.
please add @isaak654 for bug.

**Comment by ilike2burnthing** [comment]
Unfortunately we had a failure yesterday, though that was the first since last commenting - https://github.com/Jackett/Jackett/actions/runs/5960038478/job/16166697723

**Comment by isaak654** [comment]
I can confirm the [GHFileNotFoundException](https://github.com/sandboxie-plus/Sandboxie/actions/runs/6129495273/job/16711018576#step:2:85) bug in the Sandboxie Plus 1.11.2 job using Komac v1.11.0.

**Comment by vedantmgoyal9** [comment]
I'm already discussing about the occurence of this bug with @russellbanks, despite after making improvements in Komac v1.10.0. I think we should be able to fix it this time. Extremely sorry for the troubles caused.

**Comment by CodeDoctorDE** [comment]
Any updates?
I can confirm that this bug also occur on my repository:   Exception in thread "main" org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/LinwoodDev/winget-pkgs/branches/refs/heads/LinwoodCloud.Butterfly.Nightly-2.0.0-beta.9-F34C24815861C62085A3D730F4FD3EBCACFB9E25 {"message":"Branch not found","documentation_url":"https://docs.github.com/rest/branches/branches#get-a-branch"}.

https://github.com/LinwoodDev/Butterfly/actions/runs/6434665705/job/17475002842

The branch was correctly created and the link works. Rerunning doesn't fix the problem

**Comment by isaak654** [comment]
Here it is the same, the workaround I'm currently using is to manually re-run one job at a time.

**Comment by isaak654** [comment]
Here it is the same, the workaround I'm currently using is to manually re-run [one job at a time](https://github.com/sandboxie-plus/Sandboxie/actions/runs/6427917759) (although they are still shown as failed).

**Comment by isaak654** [comment]
Here it is the same, the workaround I'm currently using is to manually re-run [one job at a time](https://github.com/sandboxie-plus/Sandboxie/actions/runs/6427917759/job/17454267744#step:2:78) (although they are still shown as failed).

**Comment by russellbanks** [comment]
Hey everyone, I'm so sorry about these issues. I don't particularly know a fix for this; there's nothing code-side that would make this occur and I've never been able to reproduce this outside of GitHub actions. However, I am completely rewriting Komac in Rust - the issue shouldn't be present there.
