### ISSUE TITLE
[Bug]: Locale files (except default) get ignored

### ISSUE THREAD

**Issue by maximmax42** [vedantmgoyal2009/winget-releaser#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I don't know if this is an issue with the action or with Komac, but whenever a new version gets released, the locale files just get ignored. It used to be that the action would copy the locale files from the previous release, but now it only commits version, installer, and defaultLocale manifests.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/maximmax42/CustomRP/1.17.4 - this version had locale files right away (March 21st)
https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/maximmax42/CustomRP/1.17.5 - this version didn't have locale files, had to add them manually (April 9th)
https://github.com/microsoft/winget-pkgs/pull/103276/commits/746d3bac5f36797e0ebe67a750bb4e455a00e604 - commit for the new version has no locale files again (today)

**Comment by russellbanks** [comment]
I'll take a look today and create a new Komac release if needed

**Comment by russellbanks** [comment]
For future, WinGet Releaser just gets the URLs from the release and provides it to Komac which does everything from downloading them, analysing files, and creating the commits and pull requests, etc. If something is wrong, it's probably Komac's side as that is the one with active development.

**Comment by maximmax42** [comment]
> For future, WinGet Releaser just gets the URLs from the release and provides it to Komac which does everything from downloading them, analysing files, and creating the commits and pull requests, etc. If something is wrong, it's probably Komac's side as that is the one with active development.

Ah, I see. I'll remember that for the future.

**Comment by russellbanks** [comment]
Thanks for reporting @maximmax42. I've fixed this and have created Komac 1.5.1 with the fix. WinGet Releaser checks for Komac updates every day so will have updated to it by tomorrow.

**Comment by vedantmgoyal9** [comment]
I know the fix PR has been merged, but still just to confirm, is the issue resolved now?

**Comment by maximmax42** [comment]
Don't know, I haven't released new version yet.

**Comment by maximmax42** [comment]
Yep, works now!
