### ISSUE TITLE
[Bug]: Repeat submit PR with nothing.

### ISSUE THREAD

**Issue by 1aal** [vedantmgoyal2009/winget-releaser#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My problem is different from https://github.com/vedantmgoyal2009/winget-releaser/issues/118#issuecomment-1483887908

After one version manifest PR merged and run again in the same version, the action will not stop and will  submit an empty `update PR`

example : https://github.com/microsoft/winget-pkgs/pull/109747

**Comment by vedantmgoyal9** [comment]
Fixed in 79853c0938cc9946c1ec3cdd1b2e761bb0372b8c
