### ISSUE TITLE
[Feature/Idea]: Add support for AppsAndFeaturesEntries / DisplayVersion

### ISSUE THREAD

**Issue by ChristianGalla** [vedantmgoyal2009/winget-releaser#174]
### What would you like to see changed/added?

My project [AutoStartConfirm](https://github.com/ChristianGalla/AutoStartConfirm) uses like many other projects [semantic versioning](https://semver.org/lang/de/), a 3 part version number in the format "Major.Minor.Patch", for example "1.2.3" as release tag, release name and in winget. Unfortunately, because the version number is auto generated on each build of my C# application and MSI/Wix installer, in the background a 4 part version number in the format "Major.Minor.Patch.Build", for example "1.2.3.4" is used. This 4 part version number is also listed as version number in Apps and Features and is used by winget to check if an update is available. Because these version numbers are always different, winget's version compare and install / update suggestions are not working correctly.

There are a few more negative side effects regarding the 4 part number checking, for example if MSI is used, so I already created an [issue in the winget project](https://github.com/microsoft/winget-cli/issues/2743), but for now it es required to do one of two possible workarounds suggested in [this pull request](https://github.com/microsoft/winget-pkgs/pull/90039/files/8a4cbda577ec3df4b668bb7798d832573dcfef48#r1036393684).

To resolve the issues and keep using semantic versioning, the version number for example of an MSI installer should automatically be extracted and if it is different than the release tag should be added to the installer YAML file:
```
AppsAndFeaturesEntries:
- DisplayVersion: 1.2.3.4
```
If this is present, winget will compare this version number to the version number in Apps and Feature.

**Comment by vedantmgoyal9** [comment]
@ChristianGalla the PR created by the action already does that.

PR created from the last workflow run on your project's repo: https://github.com/microsoft/winget-pkgs/pull/110332/files already has an ARP containing `DisplayVersion`.

**Comment by ChristianGalla** [comment]
@vedantmgoyal2009 unfortunately not.

The Display Version number has been copied 1:1 from the latest winget version. I updated it in a manual commit after the action run and before the pull request has been merged: https://github.com/microsoft/winget-pkgs/commit/a1f27b1be4773201356f611f898ad3133ec8cf8c

**Comment by ChristianGalla** [comment]
It looks like this is working now: https://github.com/microsoft/winget-pkgs/pull/139289
