### ISSUE TITLE
[Bug][Sandboxie.Plus]: Winget job failed with "exceeded the maximum execution time of 360 minutes"

### ISSUE THREAD

**Issue by isaak654** [vedantmgoyal2009/winget-releaser#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/sandboxie-plus/Sandboxie/actions/runs/5336361448/attempts/1

I have no idea why the `publish-plus` job took 5h 59m.

Retrying the job solved it, could you help me understand the reason and avoid it again?

**Comment by vedantmgoyal9** [comment]
Did it occur after this issue was created? If not, then it might be a temporary issue 🤷‍♂️😶

**Comment by isaak654** [comment]
It is currently unclear when the next version of Sandboxie will be released. Is there a technical reason why the workflow does not retry the failed steps by itself?

**Comment by isaak654** [comment]
It is currently unclear when the next version of Sandboxie will be released. Is there a technical reason why the workflow does not retry the failed job(s) by itself?

**Comment by vedantmgoyal2009** [comment]
@russellbanks I think we can implement the retry logic (which is there for creating a pull request) for downloading the installer too. Also, is there any way we can add timeout so that users don't get billed for so long workflow runtime?
