### ISSUE TITLE
[Feature/Idea]: delete branches after merge

### ISSUE THREAD

**Issue by justinmk** [vedantmgoyal2009/winget-releaser#176]
### What would you like to see changed/added?

Related: https://github.com/microsoft/winget-pkgs/discussions/110688

Can the action auto-delete branches after winget-pkgs merges the PR?

https://github.com/neovim/winget-pkgs/branches has a lot of old stale branches, which is noisy.

**Comment by sitiom** [comment]
Not sure if this works for upstream PRs, but does the "Automatically delete head branches" option work for your case?
![image](https://github.com/vedantmgoyal2009/winget-releaser/assets/56180050/9662d2af-1e95-4915-930f-f16270c3664b)

**Comment by justinmk** [comment]
> does the "Automatically delete head branches" option work for your case?

That's what I suggested in https://github.com/microsoft/winget-pkgs/discussions/110688 , but see the comments there.

**Comment by justinmk** [comment]
Nice! Thanks @vedantmgoyal2009

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @justinmk for feat

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @justinmk for feat

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @justinmk for ideas
