### ISSUE TITLE
[Bug]: https://winget-manifests-manager.vercel.app is down

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://winget-manifests-manager.vercel.app is down, and it's causing errors to recent runs such as this case: https://github.com/nushell/nushell/actions/runs/5393285840/jobs/9792811653

```
D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:5017
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://winget-manifests-manager.vercel.app/api/get-winget-packages reason: Unexpected token T in JSON at position 0
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:5017:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:76:29 {
  type: 'invalid-json'
}
```

**Comment by rcmaehl** [comment]
I also got

```return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));```

In my most recent action run. Guessing it's a one-time thing? Is there a way to not rely on the URL or just skip over it since the Winget Push was successful anyway?

**Comment by CoolPlayLin** [comment]
+1
