### ISSUE TITLE
[Feature/Idea]: Add fallback regex

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#188]
### What would you like to see changed/added?

Sometimes releases have signed assets and sometimes they don't. For example, [Vim](https://github.com/vim/vim-win32-installer/releases).
> If you do not know what to use, use the 32bit installer (use the signed one, if available).

The regex could be set to `gvim.*(x64|x86)_signed.exe$` and if none are found, it would fallback to another regex. In this case, that would be the `gvim.*(x64|x86).exe$`.

```yaml
installers-regex: 'gvim.*(x64|x86).exe$'
installers-regex-fallback: `gvim.*(x64|x86)_signed.exe$`
```

Another solution would be being able to specify what group(s) to use, or what group(s) to fallback to, etc.

For example, `gvim.*((x64|x86)_signed|(x64|x86)).exe$` contains two groups:
- (x64|x86)_signed: This group will match either "x64_signed" or "x86_signed".
- (x64|x86): This group will match either "x64" or "x86".

**Comment by vedantmgoyal9** [comment]
This can be implemented in the workflow at the vim's repository. Also, since this is only the case where we need to prefer one installer over another, I'll close it for now.
