### ISSUE TITLE
[Feature/Idea]: Add release repo

### ISSUE THREAD

**Issue by daiyam** [vedantmgoyal2009/winget-releaser#21]
### What would you like to see changed/added?

Hi,

For `VScodium Insiders`, we are using the auxiliary repository `https://github.com/VSCodium/vscodium-insiders/releases`.
We are doing so to avoid to mixup the stable and insiders versions.

So it would be good if you can add an option like: `release-repository: vscodium-insiders`

**Comment by vedantmgoyal2009** [comment]
I know your use-case and I've thought of a solution. Although it's a little complex, but still...
- Keep a WinGet workflow on vscodium-insiders repo that runs on workflow dispatch event
- Use GitHub CLI (gh) to trigger the workflow, along with sending release-tag and version
  Reference: https://cli.github.com/manual/gh_workflow_run

> **Note** the only down-side is that you'll have to add `STRONGER_GITHUB_TOKEN` again in the vscodium-insiders repo.

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @daiyam for code, ideas
