### ISSUE TITLE
[Feature/Idea]: commit listed as "Unverified"

### ISSUE THREAD

**Issue by dorssel** [vedantmgoyal2009/winget-releaser#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The automated commit + PR in winget-pkgs lists me as the author (that's fine, it is my workflow that is running after all), but the commit shows the "Unverified" badge:

![image](https://github.com/vedantmgoyal2009/winget-releaser/assets/17404029/23c97ee5-0333-4541-9286-0b5bf947db6d)

I could "fix" this by checking out the PR and force-push with signature, but is there a way (instructions?) to do this properly?

**Comment by vedantmgoyal9** [comment]
That is not a bug. The action doesn't sign commits using a GPG key. The "unverified" badge is shown because you have enabled "vigilant mode" on your GitHub account.

https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits

**Comment by dorssel** [comment]
> That is not a bug.

I've changed the title to "feature/idea". EDIT: I cannot change the labels...

> "vigilant mode"

Of course, and that's intended.

It would be nice if the action could sign (somehow), or else have some instructions on how it already can be accomplished using configuration and/or the use of other tooling.

**Comment by vedantmgoyal9** [comment]
@all-contributors please add @dorssel for ideas

**Comment by vedantmgoyal9** [comment]
This will take some time to get added, since first, it needs to be added to the tool that the action uses (Komac).

**Comment by vedantmgoyal9** [comment]
Signed commits are available now! Just replace `vedantmgoyal2009/winget-releaser@v2` with `vedantmgoyal9/winget-releaser@main`.
