### ISSUE TITLE
[Bug]: Job step failed with 'A pull request already exists' error on creating PR

### ISSUE THREAD

**Issue by rhysd** [vedantmgoyal2009/winget-releaser#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Recently I released actionlint v1.6.26. The release CI workflow reported a job failure that winget-releaser failed with the following error.

https://github.com/rhysd/actionlint/actions/runs/6223632411/job/16890173325 ([workflow](https://github.com/rhysd/actionlint/blob/2e9e3aaf722c5e19aa4256cf2a95e3f8d83a00ff/.github/workflows/release.yaml#L48-L56))

```
Failed to create pull request after 3 attempts.
  Reason: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for rhysd:rhysd.actionlint-1.6.26-E6FF29B339E573C46DBBA751B0AA3699FC3F48E7."}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request"}.

  node:internal/errors:865
    const err = new Error(message);
                ^
  
  Error: Command failed: & /usr/lib/jvm/temurin-17-jdk-amd64/bin/java -jar komac.jar update --id 'rhysd.actionlint' --version 1.6.26 --urls 'https://github.com/rhysd/actionlint/releases/download/v1.6.26/actionlint_1.6.26_windows_386.zip,https://github.com/rhysd/actionlint/releases/download/v1.6.26/actionlint_1.6.26_windows_amd64.zip,https://github.com/rhysd/actionlint/releases/download/v1.6.26/actionlint_1.6.26_windows_arm64.zip' --submit
      at checkExecSyncError (node:child_process:887:11)
      at execSync (node:child_process:959:15)
      at /home/runner/work/_actions/vedantmgoyal2009/winget-releaser/v2/dist/index.js:9888:39
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 1859,
    stdout: null,
    stderr: null
  }
```

As the error message said, the PR was actually created correctly.

https://github.com/microsoft/winget-pkgs/pull/120104

I guess there is some issue in the logic to retry creating a PR.

**Comment by vedantmgoyal9** [comment]
It has somehow started retrying to create PRs, even when the first creation was successful. This looks like it is a one-time bug, however, if it occurs again, please notify me, since I can't make out why it really happened.

Please delete all branches on https://github.com/rhysd/winget-pkgs and update your fork. Also, I recommend installing https://github.com/wei/pull on your winget-pkgs fork to automatically update it at regular intervals. This will avoid PR conflicts.

**Comment by rhysd** [comment]
Thank you for your advice. I cleaned up branches and updated the master branch.
