### ISSUE TITLE
[Bug]:  Neovim workflow failing on release-winget

### ISSUE THREAD

**Issue by trbrink** [vedantmgoyal2009/winget-releaser#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Neovim is failing to publish to winget with the error:
```
  D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9723
      `git -C winget-pkgs config --local user.name ${context.payload.sender.login}`,
                                                                            ^
  
  TypeError: Cannot read properties of undefined (reading 'login')
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9723:75
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Here is a link to the relevant output: https://github.com/neovim/neovim/actions/runs/3110590152/jobs/5042020741#step:4:138

**Comment by vedantmgoyal9** [comment]
Please check the next workflow run. It should be resolved now. Apologies for the inconvenience caused 🙏🏻

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @trbrink for financial

**Comment by vedantmgoyal9** [comment]
Thanks a lot, @trbrink. That really means a lot to me 🙏🏻
