### ISSUE TITLE
[Bug]: Incorrect detected architectures

### ISSUE THREAD

**Issue by daiyam** [vedantmgoyal2009/winget-releaser#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

It seems that since few days that the architectures of the installers are incorrectly detected:

https://github.com/microsoft/winget-pkgs/pull/124421
https://github.com/microsoft/winget-pkgs/pull/125471

@russellbanks Do you want to open a bug for Komac?

**Comment by russellbanks** [comment]
Having a quick look at the release, I think this is because the release itself didn't have any x86 installers, so Komac tries it's best to pair up the given installers to the previous installers.
