### ISSUE TITLE
[Feature/Idea]: Add support for portable zip installer packages

### ISSUE THREAD

**Issue by ST-DDT** [vedantmgoyal2009/winget-releaser#288]
### What would you like to see changed/added?

Winget has a feature that allows installing exe's contained in a zip aka portable apps.
It would be nice, if that package type would be supported.

See here for an example of such a portable app installer config:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/h/Hashicorp/Terraform/1.7.1/Hashicorp.Terraform.installer.yaml

**Comment by vedantmgoyal9** [comment]
This can be done by setting `installers-regex` to `\.zip$`. Please try and let me know if there are any issues.

**Comment by ST-DDT** [comment]
Oh I have missed the part in the docs that mentions reusing existing versions.

Maybe add that as an explicit requirement section instead of putting it in the getting started guide or mention it in the config section again that the other "properties" are taken from previous versions.

The linked website seems to be down: https://docs.bittu.eu.org/winget-releaser-playground

**Comment by ST-DDT** [comment]
Thanks for your time.

**Comment by vedantmgoyal9** [comment]
> Oh I have missed the part in the docs that mentions reusing existing versions.
> 
> Maybe add that as an explicit requirement section instead of putting it in the getting started guide or mention it in the config section again that the other "properties" are taken from previous versions.
> 
> The linked website seems to be down: https://docs.bittu.eu.org/winget-releaser-playground

@ST-DDT The link is working now.

**Comment by ST-DDT** [comment]
Thanks. Have a nice week 👋

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @ST-DDT for doc, ideas
