### ISSUE TITLE
[Bug]: Action fails when winget-pkgs fork is outdated

### ISSUE THREAD

**Issue by rhysd** [vedantmgoyal2009/winget-releaser#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

I'm using this action for actionlint. Today I released v1.6.27 and found the action continued to fail on my release workflow.

[Full log](https://github.com/rhysd/actionlint/actions/runs/8031209834/job/21939330795)

```
  Failed to create branch from upstream default branch
  node:internal/errors:866
    const err = new Error(message);
                ^
  
  Error: Command failed: & /usr/lib/jvm/temurin-17-jdk-amd64/bin/java -jar komac.jar update --id 'rhysd.actionlint' --version 1.6.27 --urls 'https://github.com/rhysd/actionlint/releases/download/v1.6.27/actionlint_1.6.27_windows_386.zip,https://github.com/rhysd/actionlint/releases/download/v1.6.27/actionlint_1.6.27_windows_amd64.zip,https://github.com/rhysd/actionlint/releases/download/v1.6.27/actionlint_1.6.27_windows_arm64.zip' --submit
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at /home/runner/work/_actions/vedantmgoyal2009/winget-releaser/v2/dist/index.js:30079:39
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 1816,
    stdout: null,
    stderr: null
  }
```

After debugging the workflow, I somehow found that this was caused by [my outdated winget-pkgs repository](https://github.com/rhysd/winget-pkgs). I clicked 'Sync' button in the repository page and reran the workflow and it passed successfully.

To avoid this kind of issues, I'd like to suggest to synchronize fork repositories to the upstream latest before creating a new branch on it. It is possible by using this GitHub API:

https://docs.github.com/en/rest/branches/branches?apiVersion=2022-11-28#sync-a-fork-branch-with-the-upstream-repository

**Comment by vedantmgoyal9** [comment]
@allcontritbutors please add @rhysd for bug

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @rhysd for bug
