### ISSUE TITLE
[Feature/Idea]: Add maximum package versions functionality

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#3]
### What would you like to see changed/added?

This feature would be like `delete-previous-version`, except it would delete the oldest version once the amount of versions within a package have reached a maximum number.

For example, you have `package-x`, with maximum versions set to `5`:
```yaml
1.0.0
1.1.0
1.2.0
1.3.0
1.4.0
```
When the next version, say 1.5.0, is released, winget-releaser would then delete 1.0.0 in that same pull request.

This would be most useful in packages that push a lot of updates but want to keep their version history clean, as it is uncommon for users to need versions that old.
</br>

This links to https://github.com/microsoft/winget-pkgs/discussions/66854#discussioncomment-3188217:
> Quick answer; Feel free to add old versions (major and/or up to the 10 latest versions)

**Comment by vedantmgoyal9** [comment]
This will be a great addition, but I won't like to implement it now since the YamlCreate script is being re-written to perform operations on manifests more easily using parameters. I guess it will be completed in the next few months, so expect this in the action by December or maybe earlier ;)

**Comment by russellbanks** [comment]
https://github.com/microsoft/winget-pkgs/pull/83292#issuecomment-1326772608 is an notable use case where the publisher would want to start removing old nightly versions once that nightly version becomes stable. This might be quite difficult to implement as it would require some regex and logic on whether a version should be deleted or not. Automated deletion might be a better solution.
