### ISSUE TITLE
[Bug]: Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property bestMatch has not been initialized

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Issue has been happening on https://github.com/localsend/localsend/actions/runs/10146828969/job/28055818746

- Upstream issue: https://github.com/russellbanks/Komac/issues/327

**Comment by vedantmgoyal9** [comment]
The workflows should be updated to `uses: vedantmgoyal9/winget-releaser@main`, or to a commit hash along with dependabot.

**Comment by sitiom** [comment]
Thanks, I didn't notice that
- https://github.com/localsend/localsend/commit/587670b080b448e0d970d6abbfe2e2e58fcf6bd3
