### ISSUE TITLE
[Bug]: Action still not running with the latest Release v2

### ISSUE THREAD

**Issue by niStee** [vedantmgoyal2009/winget-releaser#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue reported in bug #294 is still present in the latest v2 release as of today. It may be beneficial to consider releasing a new version that incorporates the fix already available on the main branch.

**Comment by vedantmgoyal9** [comment]
Hi, it's now recommended to use `main` branch.

**Comment by lbueker** [comment]
Why is this recommended? That means that all workflows will break when you introduce a breaking change in the main branch?
