### ISSUE TITLE
[Bug]: Account for tags without `v` prefix

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

See https://github.com/rcmaehl/MSEdgeRedirect/pull/147#issuecomment-1259684677

**Comment by rcmaehl** [comment]
Merged the PR. Now getting

```
D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:4235
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Not Found
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:4235:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9700:7 {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/rcmaehl/MSEdgeRedirect/releases/tags/main',
    status: 404,
```

Removed the whole error because it's just of ton of JSON but can post it if needed.

**Comment by rcmaehl** [comment]
Nvm, you haven't actually pushed a new release so of course nothing changes

**Comment by sitiom** [comment]
@rcmaehl A workflow dispatch does not work for an action that depends on a release trigger. You can add a tag version input as a fallback to [`release-tag`](https://github.com/vedantmgoyal2009/winget-releaser#release-tag-release-tag).

**Comment by vedantmgoyal9** [comment]
* https://github.com/rcmaehl/MSEdgeRedirect/pull/184

**Comment by sitiom** [comment]
So that's the workaround for now?

**Comment by vedantmgoyal9** [comment]
Yup! Also, I have now switched to versioned tags so that these type of changes don't the workflow.

**Comment by sitiom** [comment]
> You can add a tag version input as a fallback to [`release-tag`](https://github.com/vedantmgoyal2009/winget-releaser#release-tag-release-tag).

@rcmaehl See https://github.com/rcmaehl/MSEdgeRedirect/pull/187
