### ISSUE TITLE
[Bug]: "Update manifests and publish" step fails

### ISSUE THREAD

**Issue by maximmax42** [vedantmgoyal2009/winget-releaser#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Somewhere during the "Update manifests and publish" step an error pops up:
```
Exception: D:\a\_temp\3a4ce3ca-aa78-4d4e-99aa-af5b9ba4f653.ps1:33
Line |
  33 |              throw $_.Exception.Message
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered while parsing value: S. Path
     | '', line 0, position 0.

Error: Process completed with exit code 1.
```
Full logs of the job: [logs_13.zip](https://github.com/vedantmgoyal2009/winget-releaser/files/9235251/logs_13.zip)

**Comment by vedantmgoyal9** [comment]
Can you please re-run the workflow and test if the issue is fixed now?

**Comment by maximmax42** [comment]
Yup, works now.

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @maximmax42 for bug
