### ISSUE TITLE
[Bug]: Unable to find version `latest`

### ISSUE THREAD

**Issue by chrisbra** [vedantmgoyal2009/winget-releaser#45]
### Is there an existing issue for this?

- [X] #46

### What happened?

Hi,
I noticed the winget releases started failing around 2 days ago with the following error message:
```
Unable to resolve action `vedantmgoyal2009/winget-releaser@latest`, unable to find version `latest`
```

**Comment by vedantmgoyal2009** [comment]
I had gone through all the repositories and changed the tag manually, not getting why I missed this one 🤔
