### ISSUE TITLE
Feedback/Impressions while implementing for gsudo.

### ISSUE THREAD

**Issue by gerardog** [vedantmgoyal2009/winget-releaser#47]
### What would you like to see changed/added?

Follow up to gerardog/gsudo#189, trying to use WinGet-Releaser 

- The bot retrieves ProductCode successfully for gsudo. How do I achieve the same with winget-releaser?
- Is there a *test-mode*? a way to run the releaser, make it commit on my fork, but not create the pull request to microsoft yet?
- How do I customize the output json? for example, Architecture: "neutral"

**Comment by vedantmgoyal9** [comment]
> * The bot retrieves ProductCode successfully for gsudo. How do I achieve the same with winget-releaser?

The ProductCode will be automatically found by the action.

> * Is there a _test-mode_? a way to run the releaser, make it commit on my fork, but not create the pull request to microsoft yet?

You can use https://bittu.eu.org/docs/wr-playground/. BTW, there isn't any _testing mode_ (dry-run) in the action itself.

> * How do I customize the output json? for example, Architecture: "neutral"

You need to do that manually, the action updates version, installer urls, release date, release notes url and other installer related fields like installer hash, product code, etc...

**Comment by gerardog** [comment]
I see @vedantmgoyal2009... Please add a dry-run, that wont create the pull request to msft.

Other issues I faced:
 
- See for example:
https://github.com/gerardog/gsudo/actions/runs/3278755892/jobs/5397905542
Error message not very descriptive. Actual problem was that the release was draft. Maybe add a warning to the docs that draft releases are not eligible.

- https://github.com/gerardog/gsudo/actions/runs/3300408456/jobs/5444962383
```
  remote: Permission to gerardog/winget-pkgs.git denied to gerardog.
  fatal: unable to access 'https://github.com/gerardog/winget-pkgs.git/': The requested URL returned error: 403
  HTTP 401: Personal access tokens with fine grained access do not support the GraphQL API (https://api.github.com/graphql)
  Try authenticating with:  gh auth login
```
  Problem with permissions, I will fix them. but action completed as Success, not fail.

**Comment by gerardog** [comment]
Permissions problem solved.

Now, 2 issues:
- Pull request not created: "aborted: you must first push the current branch to a remote, or use the --head flag"
   https://github.com/gerardog/gsudo/actions/runs/3300408456/jobs/5445662301#step:5:189

- The manifest says `.msi` Architecture is x64. I need to override this with `neutral`. The `.msi` is actually an x86 setup with a condition to deploy either x86 or x64 binaries.

**Comment by vedantmgoyal9** [comment]
> * Pull request not created: "aborted: you must first push the current branch to a remote, or use the --head flag"
>   https://github.com/gerardog/gsudo/actions/runs/3300408456/jobs/5445662301#step:5:189

* This will be fixed in https://github.com/actions/runner-images/issues/6446

> * The manifest says `.msi` Architecture is x64. I need to override this with `neutral`. The `.msi` is actually an x86 setup with a condition to deploy either x86 or x64 binaries.

* Once https://github.com/microsoft/winget-pkgs/pull/86008 is merged, the manifest will have separate entries for `x64` and `x86`. Instead of using `neutral`, separate architecture entries are preferred, since `neutral` involves `arm64` architecture too.
