### ISSUE TITLE
[Bug][Sandboxie.Plus]: Winget failed with "Number of InstallerUrls are not equal"

### ISSUE THREAD

**Issue by isaak654** [vedantmgoyal2009/winget-releaser#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a new [ARM64 installer](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.5.0) that needs to be supported by Winget.

Winget script:
https://github.com/sandboxie-plus/Sandboxie/blob/master/.github/workflows/winget.yml
Action failure:
https://github.com/sandboxie-plus/Sandboxie/actions/runs/3280182102/jobs/5400651111

> Run vedantmgoyal2009/winget-releaser@v1
Install powershell-yaml, clone winget-pkgs and configure remotes, update YamlCreate, download wingetdev...
Update manifests and create pull request
  Found Existing Version: 1.4.2
  Exception: D:\a\Sandboxie\Sandboxie\winget-pkgs\Tools\YamlCreate.ps1:915
  Line |
   915 |      Throw 'Number of InstallerUrls are not equal'
       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       | Number of InstallerUrls are not equal
>  
>  node:child_process:826
      err = new Error(msg);
            ^

**Comment by vedantmgoyal9** [comment]
Support for ARM64 has been added in this release, so there's one more installer. Hence, number of installers in this version were not equal to the installers in previous version, which resulted action to fail. I have added this version manually, and on the next release, action will work normally as it previously was.

**Comment by vedantmgoyal9** [comment]
* https://github.com/microsoft/winget-pkgs/pull/85295
