### ISSUE TITLE
[Bug]: Onefetch v2.13.2 failed to publish to WinGet

### ISSUE THREAD

**Issue by o2sh** [vedantmgoyal2009/winget-releaser#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

winget-releaser failed to publish the installer for onefetch's latest release:

`aborted: you must first push the current branch to a remote, or use the --head flag`
https://github.com/o2sh/onefetch/actions/runs/3356543583/jobs/5561771364#step:10:189

Thanks in advance for your help 🙏

**Comment by vedantmgoyal9** [comment]
Can you please try giving the PAT `workflow` permission so that it can update the fork?

**Comment by o2sh** [comment]
done
![image](https://user-images.githubusercontent.com/13710835/199022687-072f19aa-53af-4fe0-9654-1861879d9e41.png)

**Comment by vedantmgoyal9** [comment]
That's it! Next release should be successfully published. I'm going to close this for now, however, if there're any other problems, you can mention me again anytime.
