### ISSUE TITLE
[Feature/Idea]: Update YamlCreate to v2.2.1

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#52]
### What would you like to see changed/added?

Same as https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/938 but for WinGet Releaser and for v2.2.1.

Just a side question, is there a better means that we can use to stay up-to-date with upstream winget-pkgs changes to YamlCreate (whilst maintaining automation changes)?

**Comment by vedantmgoyal9** [comment]
YamlCreate v2.2.1 consists of user input updates, and fixes regarding Linux support so it does not need to be updated here.

**Comment by russellbanks** [comment]
@vedantmgoyal2009 [WinGet Releaser is still on 2.1.3](https://github.com/vedantmgoyal2009/winget-releaser/blob/9a8aae9dbbb928faeb232122730efcf4fce593a1/YamlCreate.ps1#L10), though.
