### ISSUE TITLE
[Bug]: aborted release should be marked as erroneous

### ISSUE THREAD

**Issue by daiyam** [vedantmgoyal2009/winget-releaser#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[In the last release of VSCodium](https://github.com/VSCodium/vscodium/actions/runs/3886027122/jobs/6631363483), there is the message `aborted: you must first push the current branch to a remote, or use the --head flag` but the the job doesn't fail when it should since the package hasn't been released.

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @daiyam for bug
