### ISSUE TITLE
[Feature/Idea]: Support for 1.4 manifests

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#82]
### What would you like to see changed/added?

Support for 1.4 manifests. Also, updating the `RelativeFilePath` should be supported in cases where the executable is inside a versioned directory. For example:
```yaml
- RelativeFilePath: bat-v0.22.1-x86_64-pc-windows-msvc\bat.exe
```

**Comment by vedantmgoyal9** [comment]
`bat-v<0.22.1>-x86_64-pc-windows-msvc`: is `0.22.1` package version? It can be difficult to find otherwise.

**Comment by sitiom** [comment]
Yes, or maybe just use regex.

**Comment by sitiom** [comment]
Meanwhile, assuming `RelativeFilePath` is static, setting the [installer-regex to `\.zip$`](https://github.com/jftuga/less-Windows/blob/12edbf7f0652c5a5bee66fb91489a8145d4901d3/.github/workflows/nightly.yml#L109) just works, right?

**Comment by russellbanks** [comment]
The next update of WinGet Releaser will use [Komac](https://github.com/russellbanks/Komac) which supports 1.4.0 manifests. I'm just working on updating the RelativeFilePath with regex.

**Comment by sitiom** [comment]
So, how do I update the `RelativeFilePath` in the new version?

**Comment by russellbanks** [comment]
> So, how do I update the `RelativeFilePath` in the new version?

The RelativeFilePath should automatically update. For example:

`RelativeFilePath: bat-v0.22.1-x86_64-pc-windows-msvc\bat.exe`

Will become (if the new version is 0.23.0, for example):

`RelativeFilePath: bat-v0.23.0-x86_64-pc-windows-msvc\bat.exe`

It does this by getting all the previous versons on winget and replacing the part of the string that contains one of those versions with the new version.
