### ISSUE TITLE
[Bug]: Manifest could not be downloaded

### ISSUE THREAD

**Issue by chrisbra** [vedantmgoyal2009/winget-releaser#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey,
for a fews days, I see the following error in the https://github.com/vim/vim-win32-installer/actions/runs/4039423513/jobs/6944142155:

```

Update manifests and create pull request
  OperationStopped: D:\a\vim-win32-installer\vim-win32-installer\winget-pkgs\Tools\YamlCreate.ps1:38
  Line |
    38 |      throw [System.Net.WebException]::new('Manifest schemas could not  …
       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       | Manifest schemas could not be downloaded. Try running the script again
  
  node:internal/errors:841
    const err = new Error(message);
                ^
````
any idea please?

**Comment by ReenigneArcher** [comment]
```txt
  OperationStopped: D:\a\Sunshine\Sunshine\winget-pkgs\Tools\YamlCreate.ps1:38
  Line |
    38 |      throw [System.Net.WebException]::new('Manifest schemas could not  …
       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       | Manifest schemas could not be downloaded. Try running the script again
  
  node:internal/errors:841
    const err = new Error(message);
                ^
  
  Error: Command failed: .\YamlCreate.ps1 '{"PackageIdentifier":"LizardByte.Sunshine","PackageVersion":"0.18.0","InstallerUrls":["https://github.com/LizardByte/Sunshine/releases/download/v0.18.0/sunshine-windows.exe"],"ReleaseNotesUrl":"https://github.com/LizardByte/Sunshine/releases/tag/v0.18.0","ReleaseDate":"2023-01-30","DeletePreviousVersion":false}'
      at checkExecSyncError (node:child_process:828:11)
      at execSync (node:child_process:899:15)
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\v1\dist\index.js:9766:34
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 5520,
    stdout: null,
    stderr: null
  }
```

Same error. It would be ideal if the fix could be included in the `@v1` tag so I can re-run my release without creating a new release.

**Comment by ilike2burnthing** [comment]
Same. Multiple retries eventually work (see mentioned issue above).

Started three days ago, after the dependabot updates were committed here.

**Comment by vedantmgoyal9** [comment]
> Started three days ago, after the dependabot updates were committed here.

But they haven't been into the `@v1` tag yet.

**Comment by ReenigneArcher** [comment]
> But they haven't been into the @v1 tag yet.

So multiple retries will work if using the v1 tag or retrying won't work? I already attempted one retry and it failed.

**Comment by ilike2burnthing** [comment]
> So multiple retries will work if using the v1 tag or retrying won't work? I already attempted one retry and it failed.

I'm using `@v1` and it took between 2 and 6 retries to get successful runs.

**Comment by ReenigneArcher** [comment]
3rd attempt worked. Thanks!

**Comment by sitiom** [comment]
Encountered this error in at least 2 repos:
- https://github.com/bloznelis/typioca/actions/runs/4051751147/jobs/6970431724
- https://github.com/pnpm/pnpm/actions/runs/4060315926/jobs/6989335300

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @chrisbra for bug
