### ISSUE TITLE
[Bug]: PR pipeline fails with Manifest Error: Optional field missing. [PackageFamilyName]

### ISSUE THREAD

**Issue by bostrot** [vedantmgoyal2009/winget-releaser#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After winget-releaser opened a PR to the winget-pkgs repo the Azure Pipeline fails with the following:

`Manifest Error: Optional field missing. [PackageFamilyName]`

Apparently, in a previous version of a manifest I created (manually), there was the `PackageFamilyName` in the installer manifest but winget-releaser does not add it.

[Here](https://github.com/microsoft/winget-pkgs/pull/95016/checks?check_run_id=10966383719) is a link to the closed PR with the full Pipeline output.

**Comment by vedantmgoyal9** [comment]
@bostrot you can re-open the PR and add `PackageFamilyName: 9891PhantomDevs.WSL2Manager_rqq3vyma0b55r` to the installer manifest manually for now.

I'm currently working on refactoring the action, and you can expect to get this fixed in the new version, which will be published soon.

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @bostrot for financial, bug
