### ISSUE TITLE
[Bug]: Tachidesk publish job failed

### ISSUE THREAD

**Issue by AriaMoradi** [vedantmgoyal2009/winget-releaser#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/Suwayomi/Tachidesk-Server/actions/runs/2885075164/workflow

**Comment by vedantmgoyal9** [comment]
* https://github.com/microsoft/winget-pkgs/pull/71015

When the above PR gets merged, please re-run the job, and it will publish the new version.

**Comment by AriaMoradi** [comment]
This workflow run is a failure for release v0.6.4, also some paths have changed in the release
