### ISSUE TITLE
[Feature/Idea]: Ability to update `RelativeFilePath`

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#99]
### What would you like to see changed/added?

Related to https://github.com/vedantmgoyal2009/winget-releaser/issues/82#issue-1558099702, https://github.com/russellbanks/Komac/issues/90

>Support for 1.4 manifests. Also, updating the `RelativeFilePath` should be supported in cases where the executable is inside a versioned directory. For example:
>```yaml
>- RelativeFilePath: bat-v0.22.1-x86_64-pc-windows-msvc\bat.exe
>```

I don't see an input that does this, so I'm assuming this hasn't been added yet.

**Comment by vedantmgoyal9** [comment]
I don't think a separate input is needed for this. You have already created an issue on Komac's repo, @russellbanks will add the feature. A simple regex replace can be done for it, where select previous match in the string, and replace it with the new version.

I'll keep the issue open until it's resolved in Komac.

**Comment by vedantmgoyal9** [comment]
* https://github.com/russellbanks/Komac/issues/90#issuecomment-1455198385

**Comment by sitiom** [comment]
Doesn't work
